// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package taskdb

import (
	"database/sql"
)

type Task struct {
	ID        int64
	Title     string
	Status    sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
