// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package taskdb

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO
    tasks (title)
VALUES
    (?) RETURNING id, title, status, created_at, updated_at
`

func (q *Queries) CreateTask(ctx context.Context, title string) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, title)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllTasks = `-- name: DeleteAllTasks :many
DELETE FROM tasks RETURNING id, title, status, created_at, updated_at
`

func (q *Queries) DeleteAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, deleteAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteById = `-- name: DeleteById :one
DELETE FROM tasks
WHERE
    id = ? RETURNING id, title, status, created_at, updated_at
`

func (q *Queries) DeleteById(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, deleteById, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteByStatus = `-- name: DeleteByStatus :many
DELETE FROM tasks
WHERE
    status = ? RETURNING id, title, status, created_at, updated_at
`

func (q *Queries) DeleteByStatus(ctx context.Context, status sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, deleteByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTasks = `-- name: GetAllTasks :many
SELECT
    id, title, status, created_at, updated_at
FROM
    tasks
ORDER BY
    CASE
        WHEN ? = 'updated' THEN updated_at
        ELSE created_at
    END DESC
`

func (q *Queries) GetAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByTitle = `-- name: GetByTitle :many
SELECT
    id, title, status, created_at, updated_at
FROM
    tasks
WHERE
    title LIKE '%' || ? || '%'
ORDER BY
    CASE
        WHEN ? = 'updated' THEN t.updated_at
        ELSE t.created_at
    END DESC
`

func (q *Queries) GetByTitle(ctx context.Context, dollar_1 sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getByTitle, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskById = `-- name: GetTaskById :one
SELECT
    id, title, status, created_at, updated_at
FROM
    tasks
WHERE
    id = ?
`

func (q *Queries) GetTaskById(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskById, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasksByStatus = `-- name: GetTasksByStatus :many
SELECT
    id, title, status, created_at, updated_at
FROM
    tasks
WHERE
    status = ?
ORDER BY
    CASE
        WHEN ? = 'updated' THEN updated_at
        ELSE created_at
    END DESC
`

func (q *Queries) GetTasksByStatus(ctx context.Context, status sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateById = `-- name: UpdateById :one
UPDATE tasks
SET
    title = ?,
    status = ?
WHERE
    id = ? RETURNING id, title, status, created_at, updated_at
`

type UpdateByIdParams struct {
	Title  string
	Status sql.NullString
	ID     int64
}

func (q *Queries) UpdateById(ctx context.Context, arg UpdateByIdParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateById, arg.Title, arg.Status, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
